# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c0255d76c943a1ee160d32dd5902ccd3e06298aed3a401e567a70865f5ddb1ec115b7aea01b800bbc6ab2228c31034a986750efa17d3149fd22fea77151f9091

test:
  secret_key_base: 76c1c8f1e893f829f8c2375a6aab5f2dc99f7719ebc7c2aae6f965639a8d3922f083f377abcd68ffca63dab3f60b4caf0a1212d211873aa9fcabfb069fd309bb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
